# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-05 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumSlug', models.SlugField()),
                ('Title', models.CharField(max_length=400)),
                ('UploadDate', models.DateField(null=True)),
                ('ReleasedDate', models.DateField(null=True)),
                ('PictureURL', models.URLField(default=b'')),
                ('NumberOfTracks', models.IntegerField(default=1)),
                ('ArtistDeezerID', models.IntegerField(default=0)),
                ('AlbumDeezerID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistSlug', models.SlugField()),
                ('Name', models.CharField(max_length=400, unique=True)),
                ('Featuring', models.CharField(max_length=400)),
                ('isBand', models.BooleanField(default=False)),
                ('Member', models.CharField(max_length=4000)),
                ('PersonalWebsite', models.CharField(max_length=400)),
                ('PictureURL', models.URLField(default=b'')),
                ('ArtistDeezerID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Content', models.TextField(max_length=1000)),
                ('Artist', models.CharField(max_length=400)),
                ('Album', models.CharField(max_length=400)),
                ('Song', models.CharField(max_length=200)),
                ('Comment_page', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayListSlug', models.SlugField()),
                ('Name', models.CharField(max_length=400)),
                ('CreatedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Artist', models.CharField(max_length=400)),
                ('Album', models.CharField(max_length=400)),
                ('Song', models.CharField(max_length=200)),
                ('RatingValue', models.IntegerField()),
                ('Rating_page', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongSlug', models.SlugField()),
                ('Title', models.CharField(max_length=200)),
                ('PictureURL', models.URLField(default=b'')),
                ('PreviewURL', models.URLField(default=b'')),
                ('SongDeezerID', models.IntegerField(default=0)),
                ('ArtistDeezerID', models.IntegerField(default=0)),
                ('AlbumDeezerID', models.IntegerField(default=0)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Album')),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to=b'profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='Songs',
            field=models.ManyToManyField(blank=True, to='musicapp.Song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='Artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Artist'),
        ),
    ]
