# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemID', models.IntegerField()),
                ('RatingType', models.CharField(max_length=128)),
                ('UserID', models.IntegerField()),
                ('RatingDate', models.DateField()),
                ('RatingValue', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
