# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Content', models.TextField(max_length=1000)),
                ('Artist', models.CharField(max_length=400)),
                ('Album', models.CharField(max_length=400)),
                ('Song', models.CharField(max_length=200)),
                ('RatingType', models.CharField(max_length=128)),
                ('ItemID', models.IntegerField()),
                ('RatingDate', models.DateField()),
            ],
        ),
    ]
