# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='Username',
            field=models.CharField(max_length=50),
        ),
    ]
