# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ItemID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='RatingDate',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='RatingType',
        ),
    ]
