# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20180211_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400, unique=True)),
                ('Featuring', models.CharField(max_length=400)),
                ('isBand', models.BooleanField(default=False)),
                ('Member', models.CharField(max_length=4000)),
                ('Rating', models.FloatField()),
                ('Comment', models.TextField()),
                ('PersonalWebsite', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('Title', models.CharField(max_length=200)),
                ('URL', models.URLField()),
                ('ReleasedDate', models.DateField()),
                ('Genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='musicapp.Genre')),
                ('Rating', models.FloatField(default=0)),
                ('Comment', models.TextField(default='')),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Artist')),
            ],
        ),
    ]
