# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_artist_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('URL', models.URLField()),
                ('UploadDate', models.DateField()),
                ('ReleasedDate', models.DateField()),
                ('Rating', models.FloatField(default=0)),
                ('Comment', models.TextField()),
                ('Artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Artist')),
                ('Genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Genre')),
                ('Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Song')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayListName', models.CharField(max_length=400)),
                ('UserID', models.IntegerField()),
                ('CreatedDate', models.DateField()),
                ('Song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.Song')),
            ],
        ),
    ]
