# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20180221_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ItemID',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='RatingDate',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='RatingType',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='UserID',
        ),
        migrations.AddField(
            model_name='rating',
            name='Album',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='Artist',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='Song',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='Username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='RatingValue',
            field=models.IntegerField(),
        ),
    ]
