# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_auto_20180222_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_page',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_page',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
