# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Rating',
            field=models.FloatField(default=0),
        ),
    ]
