# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20180223_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_page',
            new_name='Comment_page',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rating_page',
            new_name='Rating_page',
        ),
    ]
