# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_auto_20180220_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='NumberOfTracks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='album',
            name='PictureURL',
            field=models.URLField(default=''),
        ),
    ]
