# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_auto_20180222_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='Genre',
        ),
        migrations.AddField(
            model_name='song',
            name='ArtistName',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
