# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_auto_20180222_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='ReleasedDate',
        ),
    ]
