# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_remove_song_releaseddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='PictureURL',
            field=models.URLField(default=''),
        ),
    ]
