# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_song_pictureurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='AlbumDeezerID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='ArtistDeezerID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='ArtistDeezerID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='AlbumDeezerID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='ArtistDeezerID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='SongDeezerID',
            field=models.IntegerField(default=0),
        ),
    ]
